### ISSUE TITLE
POC Spiel inkl. Abrechnung und Datenmeldung (Bund)

### ISSUE THREAD

**Issue by alackerbauer** [HL7Austria/ELGA-MOPED-R5#288]
- [x] Testfall 1 KH HJ-Wien
- [x] Testfall 1 SV ÖGK Wien, SV Get Claim nur eigene
- [x] LGF Get Claim inkl. Patient (eingeschränkte Sicht), LGF $freigeben
- [x] Bund GetClaimResponse inkl. Patient (eingeschränkte Sicht)
- [x] Testfall 2 KH Ried --> Anja (Ticket #285 bzw. #5  )
- [x] Testfall 2 ÖGK OÖ --> Anja (Ticket #285 bzw. #5 )
- [x] Testfall LGF $auffordern --> Anja (Ticket #286)
- [x] Testfall Claim PDF mitsenden --> Simone (Ticket #57 )

**Comment by alackerbauer** [comment]
Draft Collections - konnten noch nicht getestet werden:

[A Bund.postman_collection.json](https://github.com/user-attachments/files/17797931/A.Bund.postman_collection.json)
[A LGF.postman_collection.json](https://github.com/user-attachments/files/17797929/A.LGF.postman_collection.json)
[A Reset-Und-Stammdaten.postman_collection.json](https://github.com/user-attachments/files/17797927/A.Reset-Und-Stammdaten.postman_collection.json)
[A Test 1 Herz-Jesu-KH.postman_collection.json](https://github.com/user-attachments/files/17797928/A.Test.1.Herz-Jesu-KH.postman_collection.json)
[A Test 1 ÖGK Wien.postman_collection.json](https://github.com/user-attachments/files/17797930/A.Test.1.OGK.Wien.postman_collection.json)

**Comment by alackerbauer** [comment]
Achtung: ein Reset löscht die CapabilityStatements UND die ValueSets ect.

**Comment by 1anja1** [comment]
[A Test 1 Herz-Jesu-KH.postman_collection.json](https://github.com/user-attachments/files/17820502/A.Test.1.Herz-Jesu-KH.postman_collection.json)
[B Test 2 Ried-KH.postman_collection.json](https://github.com/user-attachments/files/17820503/B.Test.2.Ried-KH.postman_collection.json)

**Comment by 1anja1** [comment]
[A LGF.postman_collection.json](https://github.com/user-attachments/files/17830417/A.LGF.postman_collection.json)

**Comment by alackerbauer** [comment]
Hier. die aktuellsten Versionen aller Collections - voll getestet und inkl. Visualization-Script:
[A Bund.postman_collection.json](https://github.com/user-attachments/files/17837422/A.Bund.postman_collection.json)
[A LGF.postman_collection.json](https://github.com/user-attachments/files/17837426/A.LGF.postman_collection.json)
[A Reset-Und-Stammdaten.postman_collection.json](https://github.com/user-attachments/files/17837428/A.Reset-Und-Stammdaten.postman_collection.json)
[A Test 1 Herz-Jesu-KH.postman_collection.json](https://github.com/user-attachments/files/17837427/A.Test.1.Herz-Jesu-KH.postman_collection.json)
[A Test 1 ÖGK Wien.postman_collection.json](https://github.com/user-attachments/files/17837424/A.Test.1.OGK.Wien.postman_collection.json)
[B Test 2 ÖGK OÖ.postman_collection.json](https://github.com/user-attachments/files/17837425/B.Test.2.OGK.OO.postman_collection.json)
[B Test 2 Ried-KH.postman_collection.json](https://github.com/user-attachments/files/17837423/B.Test.2.Ried-KH.postman_collection.json)
[C - Mini POC Bund.postman_collection.json](https://github.com/user-attachments/files/17837421/C.-.Mini.POC.Bund.postman_collection.json)

**Comment by alackerbauer** [comment]
Hier noch 2 upgedatete Collections mit Variablen um manuelles kopieren von IDs zu umgehen. Relevant derzeit für die Collections der Versicherungen: https://github.com/HL7Austria/ELGA-MOPED-R5/issues/306#issuecomment-2547811126
